export enum ApiEndpoints {
    REGISTRATION = 'auth/registration',
    LOGIN = 'auth/login',
    CHECK_EMAIL = 'auth/check-email',
    CONFIRM_EMAIL = 'auth/confirm-email',
    CHANGE_PASSWORD = 'auth/change-password',
    REVIEW = 'feedback',
    LOGIN_GOOGLE = '/auth/google',
    TRAINING = 'training',
    TRAINING_LIST = 'catalogs/training-list',
    USER_INFO = '/user/me',
    USER = '/user',
    UPLOAD_IMAGE = '/upload-image',
    TARIFF = '/tariff',
    TARIFF_CHECKOUT = '/tariff/checkout',
    TARIFF_LIST = '/catalogs/tariff-list',
}
